AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-app

  Sample SAM Template for todo-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest    
    Timeout: 20    
    Runtime: java17    
    Architectures:
      - x86_64
    MemorySize: 2048      
    #Tracing: Active
  #Api:
    #TracingEnabled: true
Resources:
  UserServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/userservice-1.0-aws.jar            
      FunctionName: post-user-function
      # Lambda SnapStart
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: snap      
      Environment:
        Variables:
          # Spring Cloud Function Environment Variable for function to call
          SPRING_CLOUD_FUNCTION_DEFINITION: userPutAPIHandler
          # Java Tiered Compilation Optimization
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"          
      Events:
        UserService:
          Type: Api
          Properties:
            Path: /users
            Method: post            

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserServiceApi:
    Description: API Gateway endpoint URL for Prod stage for UserServiceFunction function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users"
  UserServiceFunction:
    Description: UserServiceFunction Lambda Function ARN
    Value: !GetAtt UserServiceFunction.Arn
  UserServiceFunctionIamRole:
    Description: Implicit IAM Role created for UserServiceFunction function
    Value: !GetAtt UserServiceFunctionRole.Arn
