AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20    
    Runtime: java17
    Architectures:
      - x86_64    
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  UserServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/userservice-1.0-aws.jar      
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: userservice
      MemorySize: 2048      
      Events:
        UserService:
          Type: Api
          Properties:
            Path: /users
            Method: post            

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for UserServiceFunction function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users"
  UserServiceFunction:
    Description: UserServiceFunction Lambda Function ARN
    Value: !GetAtt UserServiceFunction.Arn
  UserServiceFunctionIamRole:
    Description: Implicit IAM Role created for UserServiceFunction function
    Value: !GetAtt UserServiceFunctionRole.Arn
